### ISSUE TITLE
Error compiling less file

### ISSUE THREAD

**Issue by jmls** [piratpartiet/drywall#1]
trying to npm start the app, I'm getting this error:

![image](https://cloud.githubusercontent.com/assets/929523/11452086/fe6275de-95d2-11e5-9bd2-53245312c3ed.png)

is this something I've missed in setup ?

**Comment by asbjornu** [comment]
@jmls I have no idea what's causing this. Have you done `npm install` first? What does `npm outdated` and `npm outdated -g` say?

**Comment by jmls** [comment]
Yes, just double-checked and npm install was run (re-ran to be on the safe side)

npm outdated is

```
Package               Current  Wanted  Latest  Location
font-awesome            4.4.0   4.5.0   4.5.0  font-awesome
grunt-contrib-uglify   0.10.1  0.10.1  0.11.0  grunt-contrib-uglify
helmet                 0.14.0  0.14.0  0.15.0  helmet
passport                0.2.2   0.2.2   0.3.2  passport
sequelize              3.14.1  3.14.2  3.14.2  sequelize
```

and npm outdated -g

```
bower                           1.6.5   1.6.8   1.6.8  /workspace/.npm/lib > bower
glob                           5.0.15   6.0.1   6.0.1  /workspace/.npm/lib > glob
node-gyp                        3.0.3   3.2.0   3.2.0  /workspace/.npm/lib > node-gyp
npm                            2.14.8   3.5.0   3.5.0  /workspace/.npm/lib > npm
yo                              1.4.8   1.5.0   1.5.0  /workspace/.npm/lib > yo
```

I have come across these issues : 

https://github.com/twbs/bootstrap/issues/13948
http://stackoverflow.com/questions/25010750/nameerror-variable-dl-horizontal-offset-is-undefined

**Comment by asbjornu** [comment]
It seems like `@dl-horizontal-breakpoint` is indeed missing from `/public/vendor/bootstrap/less/variables.less`. I have version `3.3.5` of Bootstrap (the latest of v3 seems to be `3.3.6`, which might be introducing this problem), could you try to do `npm install bootstrap@3.3.5` and see if that makes any difference?

**Comment by jmls** [comment]
```
npm install bootstrap@3.3.5
```

fixes this problem

thanks

**Comment by asbjornu** [comment]
@jmls Great!
